// @generated by hand from migrations/0001_initial/up.sql.
// When the migration changes, update this file by hand or by running
// `diesel print-schema` locally and copying the result.

diesel::table! {
    meta (key) {
        key -> Text,
        value -> Text,
    }
}

diesel::table! {
    run (id) {
        id -> Integer,
        started_at -> Text,
        output_root -> Text,
        source_image_path -> Text,
        configured_types_json -> Text,
        case_id -> Nullable<Text>,
        examiner -> Nullable<Text>,
        evidence_id -> Nullable<Text>,
        case_notes -> Nullable<Text>,
        status -> Text,
        elapsed_ms -> BigInt,
        total_files -> BigInt,
    }
}

diesel::table! {
    source (source_id) {
        source_id -> Integer,
        filename -> Text,
        output_subdir -> Text,
        total_bytes -> BigInt,
        bytes_read -> BigInt,
        files_found -> BigInt,
        status -> Text,
        duration_ms -> Nullable<BigInt>,
    }
}

diesel::table! {
    file (file_id) {
        file_id -> BigInt,
        source_id -> Integer,
        filename -> Text,
        filesize -> BigInt,
        file_type -> Text,
        img_offset -> BigInt,
        written_path -> Text,
        byte_runs_json -> Text,
        jpeg_status -> Nullable<Text>,
        jpeg_width -> Nullable<Integer>,
        jpeg_height -> Nullable<Integer>,
        jpeg_fragmentation_point -> Nullable<BigInt>,
        jpeg_has_restart_markers -> Nullable<Integer>,
        preview_status -> Text,
    }
}

diesel::table! {
    bookmark (file_id) {
        file_id -> BigInt,
        at -> Text,
    }
}

diesel::table! {
    note (note_id) {
        note_id -> BigInt,
        file_id -> BigInt,
        text -> Text,
        at -> Text,
    }
}

diesel::table! {
    best_choice (original_file_id) {
        original_file_id -> BigInt,
        chosen_file_id -> BigInt,
        at -> Text,
    }
}

diesel::table! {
    recovery_run (id) {
        id -> Integer,
        started_at -> Text,
        keep_candidates -> Integer,
        search_window -> BigInt,
        block_size -> Integer,
        min_entropy_score -> Double,
        huffman_validation -> Integer,
        finished_duration_ms -> Nullable<BigInt>,
        partials_processed -> Nullable<Integer>,
        candidates_written -> Nullable<Integer>,
    }
}

diesel::table! {
    variant (original_file_id, candidate_file_id) {
        original_file_id -> BigInt,
        candidate_file_id -> BigInt,
        rank -> Integer,
        method -> Text,
        entropy_score -> Double,
        ff_validity_score -> Nullable<Double>,
        huffman_mcu_count -> Nullable<Integer>,
        continuation_img_offset -> BigInt,
    }
}

diesel::table! {
    preview_blob (file_id) {
        file_id -> BigInt,
        codec   -> Text,
        width   -> Integer,
        height  -> Integer,
        bytes   -> Binary,
    }
}

diesel::allow_tables_to_appear_in_same_query!(
    meta,
    run,
    source,
    file,
    bookmark,
    note,
    best_choice,
    recovery_run,
    variant,
    preview_blob,
);
